architecture = "arm64"
image_architecture = "arm64-aarch64"
qemu_architecture = "aarch64"
pkg_site_architecture = "aarch64"
machine_type = "virt"
cpu_type = "cortex-a57"
firmware = "/usr/share/qemu-efi-aarch64/QEMU_EFI.fd"
